.\" Manpage for nuseradd.
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 8 "06 May 2010" "1.0" "nuseradd man page"
.SH NAME
.EX
.SH Integrates headers in files accord to extensions
.SH ==============================================================================
.SH Changelog                                       
          Created By : sdo
          File Name : MyHeadersFill_file.1
          Creation Date : 2024-01-30 00:20:50
          Last Modified : 2025-10-13 22:26:53
          Email Address : cbushdor013\[at]laposte.net
          Version : 0.0.0.398
.SH ==============================================================================
.SH CONTENTS                                                  
.SH   * Introduction 
.SH   * How to Install Plugin      
.SH   * Mapping      
.SH   * Caveats      
.SH   * Contributing 
.SH   * Changelog    
.SH   * License      
.SH   * Credits      

.SH ==============================================================================
.SH Introduction                                 

.SH Set "man" with the following command (if you shell is zsh):

.SH Go to your terminal and copy and past the two following lines (% is prompt):

.SH  %echo \[aq]export MANPATH=\[dq]$HOME/.vim/plugged/MyHeadersFill_file/man:$MANPATH\[dq];\[aq]\[rs]
.SH       >>\[ti]/.myzshrc ; source \[ti]/.myzshrc
.SH  %man MyHeadersFill_file

.SH When a file is created with a specific extension (see list below under
.SH construction) this plugin creates an appropriate header. In ˜/.vimrc the
.SH ":set nu" option is defined (to remove ":set nonu") to show line number.

.SH     1 \[dq] ------------------------------------------------------
.SH     2 \[dq] Created By :
.SH     3 \[dq] File Name :
.SH     4 \[dq] Creation Date : 2024-01-29 09:35:31
.SH     5 \[dq] Last Modified :
.SH     6 \[dq] Email Address :
.SH     7 \[dq] Version :      0.0.0.0
.SH     8 \[dq] License:
.SH     9 \[dq] Purpose :
.SH    10 \[dq] ------------------------------------------------------

.SH After saving ":w"<ret> you should have:

.SH      1 \[dq] ------------------------------------------------------
.SH      2 \[dq] Created By : foo
.SH      3 \[dq] File Name : file.txt
.SH      4 \[dq] Creation Date : 2024-01-29 09:35:31
.SH      5 \[dq] Last Modified : 2024-01-29 09:36:14
.SH      6 \[dq] Email Address : my.email\[at]my_email.net
.SH      7 \[dq] Version :  0.0.0.1
.SH      8 \[dq] Licence :
.SH      9 \[dq] ...  Attribution-NonCommercial 3.0 ...
.SH     10 \[dq] ...  http://creativecommons.org/licenses/by-nc/3.0/ ...
.SH     11 \[dq] Purpose :
.SH     12 \[dq] ------------------------------------------------------

.SH ==============================================================================
.SH How to Install Plugin                             

.SH Technical requirements
.SH     * Vim (text editor): Version 90.1050.
.SH     * System macOS: Version 132.1 (22D68).
.SH     * System Fedora: Version 38beta (Should work on other linux distros too)
.SH     * Scripts: Markdown, Vim Script, shell sh
.SH     * Vim plugin: Vim-plug

.SH Note
.SH Should be alright, as long as Vim Script is supported by the editor
.SH (since version 8.0).
.SH You can use both ways to enlight text or have basic text like this:

.SH          Text enlighted        Basic text
.SH          ":syntax on"            ":syntax off"
.SH          ":set filetype=help"    ":set filetype=text"
.SH          ":syntax enable"

.SH Notation use
.SH   <C-key>: Combination of Control key + another key.

.SH How to start
.SH   We admit that Vim-plugin is already installed. If not so, go to
.SH   https://github.com/junegunn/vim-plug and follow instructions.

.SH   We configure \[ti]/.vimrc below (\[ti] means home directory same story for
.SH   the environment variable ${HOME}):

.SH      call plug#begin(\[aq]\[ti]/.vim/plugged\[aq])
.SH      Plug \[aq]cbushdor/MyHeadersFill_file\[aq]
.SH      call plug#end()

.SH   and plugin will be installed in \[ti]/.vim/plugged if everything is well
.SH   configured. Then type ":wq" to save and, \[ga]:source \[ti]/.vimrc\[ga] to relaunch.
.SH   Then, type ":PlugInstall" and, look if plugin is installing itself.
.SH   If, plugin already installed hence ":PlugUpdate".
.SH   It shoulb be in ${HOME}/.vim/plugged/MyHeadersFill_file/. Later on,
.SH   we will refer to this path as <my_home_plugin>.
.SH   A prompt might ask not to forget to set in ˜/.vimrc the variable email:

.SH      let g:myEmail=\[aq]my.email\[at]my_email.net\[aq]

.SH   WATCHOUT OUT! After installing the plugin, when you open a file for
.SH   the first time (after plugin installed succesfully), a prompt may
.SH   ask to set an email and, may set it in the file \[ti]/.vimrc
.SH   for you. Sometime we have $MYVIMRC that contains the path.
.SH   Check:
.SH                ":!echo $MYVIMRC"

.SH   This can be changed with the command ":MyHeadersFillFileChangeEmail".
.SH   Just follow prompt instructions!

.SH   The final test is to create a text file in a specific directory s.a
.SH   ˜/Downloads:

.SH       % cd ˜/Downloads
.SH       % vim file.txt

.SH    you should have the following (if ":set nu" is set):

.SH     1 \[dq] ------------------------------------------------------
.SH     2 \[dq] Created By :
.SH     3 \[dq] File Name :
.SH     4 \[dq] Creation Date : 2024-01-29 09:35:31
.SH     5 \[dq] Last Modified :
.SH     6 \[dq] Email Address :
.SH     7 \[dq] Version :      0.0.0.0
.SH     8 \[dq] License:
.SH     9 \[dq] Purpose :
.SH    10 \[dq] ------------------------------------------------------

.SH   After saving ":w"<ret> you should have something similar!

.SH     1 \[dq] ------------------------------------------------------
.SH     2 \[dq] Created By : foo
.SH     3 \[dq] File Name : file.txt
.SH     4 \[dq] Creation Date : 2024-01-29 09:35:31
.SH     5 \[dq] Last Modified : 2024-01-29 09:36:14
.SH     6 \[dq] Email Address : my.email\[at]my_email.net
.SH     7 \[dq] Version :  0.0.0.1
.SH     8 \[dq] Licence :
.SH     9 \[dq] ...  Attribution-NonCommercial 3.0 ...
.SH    10 \[dq] ...  http://creativecommons.org/licenses/by-nc/3.0/ ...
.SH    11 \[dq] Purpose :
.SH    12 \[dq] ------------------------------------------------------



.SH  MEANINGS OF FIELDS
.SH    The header is created if file is new and, file type extension supported.
.SH    If file already exists, but doesn\[aq]t have any header, you can create one.
.SH    Follow this:
.SH    - Go to first line by typing \[ga]:1" and then type "i\[ga] to be in
.SH      insert mode. This method should work wherever your cursor is
.SH      but, shebang line won\[aq]t show up!
.SH    - Type <C-c> (Control-c) a header will show up at first line
.SH      in the current file with shebang according to file extension.
.SH      It will be saved after ":w"<ret>.
.SH    - According to some file type instead of header a script to
.SH      document file will show up as. These files are stored in
.SH      <my_home_plugin>/headers/<file_extenstion>_doc_header.txt.
.SH      List of headers look for
.SH      <my_home_plugin>/headers/<file_extenstion>_header.txt.



.SH    !--------------!-------------------------------!---------------------------
.SH    !Field name    !Use                            !Update time
.SH    
.SH    !Created By    !User name.                     !At file creation.
.SH    !--------------!-------------------------------!---------------------------
.SH    !File Name     !File name.                     !At file creation. Cannot be
.SH    !              !                               !changed except, if file
.SH    !              !                               !name itself is changed.
.SH    !              !                               !Updated automatically.
.SH    !--------------!-------------------------------!---------------------------
.SH    !reation Date  !Date when file is created.     !At file creation.
.SH    !--------------!-------------------------------!---------------------------
.SH    !ast Modified  !Date when file is Modified.    !Updated when file is saved.
.SH    !--------------!-------------------------------!---------------------------
.SH    !mail Address  !Email of the user.             !Can be changed within read
.SH    !              !                               !!MyHeadersFill_file...
.SH    !              !                               !_Install!.
.SH    !--------------!-------------------------------!---------------------------
.SH    !Version       !This is the version number.    !Only last field incremented
.SH    !              !                               !when file is saved.
.SH    !--------------!-------------------------------!---------------------------
.SH    !License       !Your choice.                   !Can be changed anytime!
.SH    !--------------!-------------------------------!---------------------------
.SH    !Purpose       !Why this file was created.     !Can be changed anytime!
.SH    !--------------!-------------------------------!---------------------------

.SH ==============================================================================
.SH Mapping                                           

.SH    Follow these steps if you are in normal mode:

.SH          - MyHeadersFillFileAddHeaderTopFile
.SH          - MyHeadersFillFileChangeEmail

.SH    Follow these steps if you are in insert mode:

.SH          - Type <C-h> (Control-h) a header will be created
.SH            at first line of the file acording to file
.SH            extension.

.SH          - Type <C-c> (Control-c) a header will be created
.SH            where the cursor is in in the file. According to
.SH            file extension (if it is supported) the header will
.SH            contains shebang.
.SH            If file with extension already exists, but that
.SH            does not have header and, if cursor is at first
.SH            line in file, header will be added with proper
.SH            shebang.

.SH          - Type <C-c> on the line while in insert mode
.SH               145 I<Last modification:> 2025-09-10 20:35:37

.SH            and fild will be updated like this:
.SH               145 I<Last modification:> 2025-09-10 20:36:23


.SH          - Type <C-c> (Control-c) a header will be created
.SH            where the cursor is in in the file. In that case, if
.SH            file as an extension, might add documenttion tag.
.SH          - Header and documentation can be found in:
.SH            ${HOME}/.vim/plugged/MyHeadersFill_file/headers
.SH            <script_name>_header.txt: holds header
.SH            <script_name>_doc_header.txt: holds documentation


.SH ==============================================================================
.SH LICENSE                                           

.SH    Attribution-NonCommercial 3.0 Unported (CC BY-NC 3.0)

.SH    Permission is granted to copy, distribute, and/or modify this document
.SH    under the terms of the Creative Commons Attribution-NonCommercial 3.0
.SH    Unported License, which is available at
.SH    http://creativecommons.org/licenses/by-nc/3.0/.


.SH ==============================================================================
.SH Caveats                                           


.SH    - If a file is closed with :x command, fields are not updated properly.
.SH    - If header does not exist in the file, when file is saved we have error
.SH    messages that are printed.


.SH ==============================================================================
.SH Contributing                                 


.SH    - GitHub:  https://github.com/cbushdor/MyHeadersFill_file
.SH    - Vim: https://www.vim.org/
.SH    - System macOS: Version 13.2.1 (22D68).
.SH    - System Fedora: Version 38beta (Should work on other linux distros too).


.SH ==============================================================================
.SH Credits                                           

.SH    Based on \[dq]Vi and Vim Autocommand: 3 Steps to Add Custom Header To Your File
.SH    Automatically\[dq].


.SH vim:tw=78:ts=15:ft=help:norl:
.EE
